config/routes.rb
Rails.application.routes.draw do

 root 'homes#top'
 root 'books#top'
 get 'books' =>'books#index'
 post 'books' =>'books#create'
 get 'books/:id' =>'books#show', as: 'book'
 get 'books/:id/edit' => 'boos#edit', as: 'edit_book'
 patch 'books/:id' => 'books#update', as: 'update_book'
 delete 'books/:id' =>'book#destroy', as: 'destroy_book'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books=Book.all
    @book=Book.new(book_params)
  end

  def show
    @book=Book.find(params[:id])
  end

  def create
    @book=Book.new(book_params)
    if @book.save
      redirect_to book_path(book:id)
    else
      render :new
    end
  end

  def edit
    @book=Book.find(params[:id])
  end

  def update
   @book=Book.find(params[:id])
   book.update(bookt_params)
    redirect_to book_path(book:id)
  end

  def destroy
    @book=Book.find(params[:id])
    @book.destroy
    redirect_to book_path
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>
<%= form_with model:@book, url:"/books/#{@book.id}", local:true do |f| %>

<h4>Title</h4>
<%= f.text_field :title %>

<h4>Body</h4>
<%= f.text_area :body %>

<%= f.submit 'Create Book' %>

<%= link_to "Show",show_book_path(@book.id) %>
"|
"
<%= link_to "Back",index_book_path(@book.id) %>

<% end %>

app/views/books/index.html.erb
<h3>Books</h3>

<table>
  <thead>
    <tr>
      <th>title</th>
      <th>title</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <%= book.each do |book| %>
    <tr>
      <td>
        <%= book.title %>
      </td>
      <td>
        <%= book.body %>
      </td>
      <td>
        <%= link_to "Show",book_path(book.id) %>
        <%= link_to "Edit",edit_book_path(book.id) %>
        <%= link_to "Destroy",destroy_book_path(book.id), method: :delete, "data-confirm" => "Are you sure?" %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

<h3>New book</h3>

<%= from_for(@book) do |f| %>

<h4>Title</h4>
<%= f.text_field :title %>

<h4>Body</h4>
<%= f.text_area :body %>

<br><%= f.submiot 'Create Book' %></br>

<% end %>

app/views/books/new.html.erb
<h1>Books#new</h1>
<p>Find me in app/views/books/new.html.erb</p>

app/views/books/show.html.erb
<h2>Title</h2>
<p><%= @book.title %></p>
<h2>Body</h2>
<p><%= @book.body %></p>

<%= link_to "Edit",edit_book_path(@book.id) %>
"|
"
<%= link_to "Back",index_book_path(@book.id) %>

app/views/homes/top.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="books.css">
    <title>bookers</title>
  </hea

  <body>
    <h1>ようこそ <b>Bookers</b>  へ！</h1>
    <p><b>Bookers</b>  では、さまざまな書籍に関するあなたの意見や</p>
    <p>印象を共有し交換することができます</p>
    <p><a href="/books">start</a></p>

  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>